version: '3'
services:

  # PHP-FPM (FastCGI Process Manager) service
  phpfpm:
    image: 'bitnami/php-fpm'
    container_name: php-fpm
    ports:
        - '9000:9000'
    volumes:
        - ./public:/myprojects
    networks:
      - app-network

  # NGiNX service
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ./public:/myprojects
    networks:
      - app-network

  # MariaDB service
  mysql:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    ports:
        - "3306:3306"
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=ncklinux_root
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
